name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch tags
      run: git fetch --tags --force
    - name: Fetch release body from tag
      uses: ericcornelissen/git-tag-annotation-action@v2
      id: tag-data
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version: 'stable'
    - name: Build for darwin/arm64
      run: env GOOS=darwin GOARCH=arm64 go build -o "anchor_darwin-arm64" -ldflags "-X github.com/loghinalexandru/anchor/internal/command.version=$GITHUB_REF_NAME" .
    - name: Build for darwin/amd64
      run: env GOOS=darwin GOARCH=amd64 go build -o "anchor_darwin-amd64" -ldflags "-X github.com/loghinalexandru/anchor/internal/command.version=$GITHUB_REF_NAME" .
    - name: Build for linux/amd64
      run: env GOOS=linux GOARCH=amd64 go build -o "anchor_linux-amd64" -ldflags "-X github.com/loghinalexandru/anchor/internal/command.version=$GITHUB_REF_NAME" .
    - name: Build for windows/amd64
      run: env GOOS=windows GOARCH=amd64 go build -o "anchor_windows-amd64" -ldflags "-X github.com/loghinalexandru/anchor/internal/command.version=$GITHUB_REF_NAME" .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "anchor*"
        body: ${{ steps.tag-data.outputs.git-tag-annotation }}